export default [
  '300+ React Interview Questions',
  'Awesome Things Related To React Hooks 😍',
  '33 React Libraries Every React Developer Should Have In Their Arsenal',
  'The Most Powerful React JS Cheat Sheet ',
  'Full list of React Conferences in 2020 👩‍🏫 ⚛️ 🤝 ⚛️ 👨‍🏫',
  'React Awesome Components',
  'Node.js File System API - beginner-friendly guide',
  'ES modules in Node today',
  'What you need to know about ES modules in Node.js',
  'NodeJS: How To Use The URL Module',
  'Nodejs JWT Authentication - Nodejs/Express RestAPIs + JSON Web Token + BCryptjs + Sequelize + MySQL\n',
  'NodeJS logging made right',
  'NodeJS: How To Read A JSON File From Your Machine',
  'Make your JavaScript Typed Safe',
  'JavaScript Jabber Podcast',
  'Resources to Master Javascript',
  'Useful Javascript links - Interview preparation Part-1',
  '50 Web Development Projects for Beginners - JSAyushThakur',
  'Front-End Resources',
  'Cheeriojs. Jordan Teaches Web Scraping',
  '33 JavaScript Concepts Every Developer Should Know 🤓️💯️',
  'How to create a web page with HTML',
  'HTML Deep',
  '10 useful HTML5 features, you may not be using',
  'Myth HTML5 is not a programming language',
  '7 Alternatives to the div Tag in HTML',
  '10 GitHub repos based on HTML',
];
